sudo: required
language: generic
services:
  - docker

#test version
before_install:
  - docker build -t jsheikh/react-test -f ./client/Dockerfile.dev ./client
  #docker build myotherprohects
#primary test running section
script:
  - docker run -e CI=true jsheikh/react-test npm test
  #docker run myotherprohects

#production version images
after_success:
  - docker build -t jsheikh/multi-client ./client
  - docker build -t jsheikh/multi-nginx ./nginx
  - docker build -t jsheikh/multi-server ./server
  - docker build -t jsheikh/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jsheikh/multi-client
  - docker push jsheikh/multi-nginx
  - docker push jsheikh/multi-server
  - docker push jsheikh/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-593185665098'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"